# base theme (light, dark, intellij, darcula, maclight or macdark); only used by theme editor
# Author: Purple Nebula (SRT Revised)
@baseTheme = dark

@accentBaseColor = #813737
@accentSelectionBackground = @accentBaseColor
@accentButtonDefaultBackground = @accentBaseColor

