# base theme (light, dark, intellij, darcula, maclight or macdark); only used by theme editor
@baseTheme = dark

@background = #002521
@accentBaseColor = #27ecce
@accentSelectionBackground = #27ecce
@accentButtonDefaultBackground = #27ecce
@buttonBackground = #00473e
@menuBackground = #00473e
ComboBox.background = #00473e
