# base theme (light, dark, intellij, darcula, maclight or macdark); only used by theme editor
# Author: Purple Nebula (SRT Revised)
@baseTheme = dark

@background = #27221C

@accentBaseColor = #D8AD73
@accentSelectionBackground = @accentBaseColor
@accentButtonDefaultBackground = @accentBaseColor

@buttonBackground = #535048
@menuBackground = @buttonBackground
ComboBox.background = @buttonBackground