# base theme (light, dark, intellij, darcula, maclight or macdark); only used by theme editor
@baseTheme = dark

@accentBaseColor = #6f42f5
@accentSelectionBackground = #6f42f5
@accentButtonDefaultBackground = #6f42f5