# base theme (light, dark, intellij, darcula, maclight or macdark); only used by theme editor
# Author: Purple Nebula (SRT Revised)
@baseTheme = dark

@background = #002521

@accentBaseColor = #27ecce
@accentSelectionBackground = @accentBaseColor
@accentButtonDefaultBackground = @accentBaseColor

@buttonBackground = #00473e
@menuBackground = @buttonBackground
ComboBox.background = @buttonBackground
