# base theme (light, dark, intellij, darcula, maclight or macdark); only used by theme editor
# Author: Purple Nebula (SRT Refurbished)
#433781
@baseTheme = dark

@background = #0e0024

@accentBaseColor = #6f42f5 
@accentSelectionBackground = @accentBaseColor
@accentButtonDefaultBackground = @accentBaseColor

@buttonBackground = #4c4853
@menuBackground = @buttonBackground
ComboBox.background = @buttonBackground