# base theme (light, dark, intellij, darcula, maclight or macdark); only used by theme editor
@baseTheme = dark

@background = #27221C
@accentBaseColor = #D8AD73
@accentSelectionBackground = #D8AD73
@accentButtonDefaultBackground = #D8AD73
@buttonBackground = #535048
@menuBackground = #535048
ComboBox.background = #535048